# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
    -   id: pylama
        name: pylama
        args: [--max-line-length=120]
        entry: pylama
        language: system
        types: [ python ]